name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
        node-version: [10.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: build
        run: |
          yarn install
          yarn run build:prod
          yarn run install:python

      - name: test
        run: MOCHA_WEBDRIVER_HEADLESS=1 yarn run test
